### PR TITLE
check 'name' field is a string type for about msgs

### PR DESCRIPTION
**Pull request by noffle**
addresses https://github.com/ssbc/scuttlebot/issues/472

### CODE REVIEW

**Comment by noffle** [comment]
Also: any objections to moving this repo to the ssbc org so we can push emergency fixes?

**Comment by evbogue** [comment]
no objections. Thanks for figuring this one out @noffle !

**Comment by dominictarr** [comment]
ah yeah, people started using about messages for everything... merging. will shift to ssbc too

**Comment by dominictarr** [comment]
note, this changes the code for the index, so requires the index to rebuild, but it doesn't change the api, so it's just a patch version.

**Comment by dominictarr** [comment]
merged into 3.0.2

**Pull request merged**
